InternationalTradeAdministration/ita-powerbi-gateway

app.js, client/package-lock.json, client/package.json, client/src/utils/Repository.js, package-lock.json, package.json
Should also resolve security vulnerabilities reported by GitHub
=> Updated Standard JS and fixed some syntax

README.md, client/package-lock.json, client/package.json, client/src/App.vue, client/src/Groups.vue, client/src/ReportViewer.vue, client/src/Reports.vue, client/src/router/index.js, client/src/utils/Repository.js, config/config.js, routes/controllers/reporting.js, routes/routes.js, services/utils.js
- The service principle must be a member of the workspace for this to work
=> [MDS-346] Users may view reports in different powerbi workspaces

src/main/resources/db/migration/V1.00.16__Update_SIMA.sql
- Add CREATED_AT to SIMA tables and views
=> [MDS-367] SIMA user sees footnote that contains last modified dates on licensing data and census data

src/main/resources/db/migration/V1.00.17__Update_Aero.sql
- Use the new set of files from J.A.
- Remove all the historical data
=> [MDS-443] Update Aerospace data

client/src/reports/OtexaAnnual.vue
- HTS numbers, Chapters, Categories, and Countries
=> [10433] Sort the options in alphanumeric ascending order

client/src/reports/OtexaAnnual.vue
Reverts InternationalTradeAdministration/ita-powerbi-gateway#52
=> Revert "[10433] Sort the options in alphanumeric ascending order"

src/main/resources/db/migration/V1.00.25__OTEXA_Post_Processing.sql
Reverts InternationalTradeAdministration/ita-powerbi-gateway#54
=> Revert "Revert "[9220] Updated OTEXA Footwear post processing v2""

client/src/reports/OtexaAnnual.vue
Reverts InternationalTradeAdministration/ita-powerbi-gateway#53
=> Revert "Revert "[10433] Sort the options in alphanumeric ascending order""

client/src/reports/OtexaAnnual.vue
Reverts InternationalTradeAdministration/ita-powerbi-gateway#56
=> Revert "Revert "Revert "[10433] Sort the options in alphanumeric ascending order"""

client/src/reports/OtexaAnnual.vue
* Include it as an optional dataset source
=> [11472] Fix broken filters on embedded reports that use the OTEXA_ANNUAL_OPT_HTS_VW table

src/main/resources/db/migration/R__1.00.01_CreateFlattenSIMAAluminumJSONStoredProcedure.sql, src/main/resources/db/migration/V1.00.26__CreateSimaAluminumTable.sql
- add SIMA_ALUMINUM table
- stored procedure to flatten JSON
=> [9446] SIMA sees aluminum data in MDS

src/main/java/gov/ita/powerbi_gateway/public_data/otexa/HtsRepository.java, src/main/java/gov/ita/powerbi_gateway/public_data/otexa/ProductionMetadataService.java
- They were already sorted when selecting by Category, but this edit ensures they are sorted when selecting by Chapter, too
=> [10433] Sort the HTS codes in the list numerically

client/src/reports/OtexaAnnual.vue, src/main/resources/db/migration/R__1.00.03_OTEXA_Annual_VW.sql
- Overwrite the VW name in preparation for [11913] major shippers report
=> Cleanup VW names

client/src/reports/OtexaAnnual.vue
- For the Major Shippers Reports, static views
=> [11913] Create a view of reports that hides filters

src/main/resources/db/migration/V1.00.31__SIMA_STEEL_Concordance_Update.sql
- Product Group Name for Group 58 corrected
- Group Numbers added to all rows
=> [12458] Correct Product Group 58 and make each row have number

src/main/resources/db/migration/V1.00.31__SIMA_STEEL_Concordance_Update.sql
HTS Code data type changed to INT
=> [12458] Fix HTS Code data type for SIMA Steel Concordance

src/main/resources/db/migration/V1.00.39__Update_Aero.sql
Import the individual files Jonathan uploads, add Trade Flow column, and append in PowerBI report.
Remove the old quarterly table.
=> Revise schema for uploading quarterly data

src/main/java/gov/ita/powerbi_gateway/powerbi_admin/PowerBiAdminController.java, src/main/java/gov/ita/powerbi_gateway/powerbi_admin/PowerBiAdminService.java
- refresh access token in order to obtain a fresh embed token
=> [12374] PowerBI Gateway client needs to refresh embed token

src/main/resources/db/migration/V1.00.47__UpdateSIMACensusVW.sql
- Remove Line Pipe normalization
- Trim trailing ... from commodity descriptions
=> [12965] Update SIMA Census VW to reflect changes in commodity description

client/src/reports/OtexaAnnual.vue, src/main/resources/db/migration/R__1.00.16_OtexaAnnualFootwearView.sql
- Include categories that don't have associated chapter and HTS codes
- Edit "Display In" options in the pre-filter step
=> [11039] Otexa Annual Footwear data - update view and vue

.gitignore, src/main/resources/db/migration/R__1.00.19_UpdateSIMAReaderViews.sql
Fix SIMA_CENSUS_VW to remove duplicates
=> [13265] Remove SIMA_CENSUS_VW duplicates

client/src/ReportFactory.vue, client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaMsrFootwearCategories.vue, src/main/resources/db/migration/R__1.00.20_Update_Otexa_Annual_FootwearVW.sql
- Filter Chapters for Footwear to a particular list
- Display the "Display In" selection in a consistent way
- Update Annual Footwear View to populate HTS list from Category & Chapter selection in pre-filter
=> [13893] Update Otexa Report Views

client/src/reports/OtexaAnnual.vue, src/main/java/gov/ita/powerbi_gateway/public_data/otexa/YearRepository.java, src/main/resources/db/migration/V1.00.56__CreateOtexaReportingMonth.sql
- Also, change display order of years returned by YearRepository
- Adjust width of select menu
=> [13882] Otexa users can retrieve reporting month in MDS

src/main/resources/db/migration/R__1.00.03_OTEXA_Annual_VW.sql
Reverts InternationalTradeAdministration/ita-powerbi-gateway#129
=> Revert "[15146] Revise SME Current Month calculation"

src/main/resources/db/migration/R__1.00.03_OTEXA_Annual_VW.sql
Reverts InternationalTradeAdministration/ita-powerbi-gateway#131
=> Revert "[15146] DG28/Current Month: SYEF/SME conversion"

src/main/resources/db/migration/R__1.00.20_Update_Otexa_Annual_FootwearVW.sql
Reverts InternationalTradeAdministration/ita-powerbi-gateway#134
=> Revert "[15514] Fix for HTS codes not populating when Category selected in pre-filter"

client/src/reports/OtexaAnnual.vue
If searching by Category, then Category & HTS tab defaults to Country = World.
If searching by Country, then Country tab defaults to Category = 0.
=> [15776] Otexa annual report template adds page level filters

client/src/reports/OtexaAnnual.vue
- We don't want to omit these from the dataset altogether, just hide them here
=> [16208] Add Page-level filter to HTS page to hide rows where HTS is blank

client/src/reports/OtexaAnnual.vue
=> [17178] Otexa: Fix for disappearing years when toggle Country/Category

src/main/resources/db/migration/R__1.00.33__CreataSimaDownstreamSteelHtsCodesView.sql
- add [sima_steel_reader].[SIMA_DOWNSTREAM_STEEL_HTS_CODES] view
=> [17122] Report writer sees downstream steel data with new concordance

src/main/resources/db/migration/R__1.00.22_CreateSIMAAluminumConcordance.sql
=> [17375] Fix discrepancies on SIMA aluminum data

client/src/reports/OtexaMergedPartCat.vue
- Not allow multiple countries selected
- Category select menu expanded to show full label
- Hide filter on the PBI report
- Expand all options for "Data By" so it's no longer a drop down menu
=> [19068] Otexa: Part & Merge Cat report edits

client/src/reports/OtexaMsrCountries.vue
- disable selecting multiple countries
=> [19066] Otexa: MSR Country edits

client/src/reports/OtexaMergedPartCat.vue
- Category & HTS tabs default to filter on World
- Correct filtering for Countries
=> [19068] Otexa: Part/Merg Cat report filter bug fixes

client/src/reports/OtexaMergedPartCat.vue
=> [19068] Otexa: Merge/Part Category Bugfixes

client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaExportFootwear.vue, client/src/reports/OtexaExports.vue, client/src/reports/OtexaMergedPartCat.vue, client/src/reports/OtexaMsrCategories.vue, client/src/reports/OtexaMsrCountries.vue, client/src/reports/OtexaMsrFootwearCategories.vue
=> [19068] Otexa: Part/Merge Cat: disable multiple category selection

client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaExportFootwear.vue, client/src/reports/OtexaExports.vue, client/src/reports/OtexaMsrCategories.vue
- Also make MSR Categories layout flex-wrap
=> Otexa: Make "Data By" selection appear as a list for consistency

src/main/resources/db/migration/R__1.00.24_OtexaMergedAndPartCatView.sql, src/main/resources/db/migration/V1.00.89__OtexaAddColumnMergedCat.sql
~(note: this PR will be rebased after #196)~ done
=> [19477] Otexa: Merged Category Report - add column for HTS

client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaExportFootwear.vue, client/src/reports/OtexaExports.vue, client/src/reports/OtexaMergedPartCat.vue
- Because can't prevent them from only appearing on the correct page on first render
=> [19795] Otexa users: hide page level filters

src/main/resources/db/migration/R__1.00.24_OtexaMergedAndPartCatView.sql, src/main/resources/db/migration/V1.00.91__OtexaAddUnitsToPartCat.sql
=> [19342] Otexa: Part Category data adds unit columns

client/src/reports/OtexaMsrCountries.vue, client/src/reports/OtexaMsrFootwearCategories.vue
- Footwear Import MSR Category:
- Add Category 19 “All Travelgoods” to the selection screen
- Flex the “Display In” box so it appears to the right of the travelgoods box
- Footwear Import MSR Country:
- On the selection screen, change the "Display In" drop-down to list-style
=> [19952] Otexa: Updates to Footwear Imports MSR report pre-filter templates

src/main/resources/db/migration/R__1.00.20_Update_Otexa_Annual_FootwearVW.sql, src/main/resources/db/migration/R__1.00.37_CreateOtexaExportFootwearView.sql, src/main/resources/db/migration/V1.00.93__OtexaAddDollarSignFootwear.sql
- Also incorporate the Quantity column from the raw data into the reporting view
=> [20119] Otexa Footwear Imports adds dollar sign column

client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaAnnualFootwearDivided.vue
- Navigate between pages using button bookmarks
=> [20121] Otexa Annual/Footwear - Hide page nav, multi-select countries

src/main/resources/db/migration/R__1.00.20_Update_Otexa_Annual_FootwearVW.sql
- HTS Chapter ref has Source column that needs to be joined on now
=> [21156] Otexa Footwear Imports: Update reporting view

src/main/java/gov/ita/powerbi_gateway/public_data/otexa/Hts.java, src/main/java/gov/ita/powerbi_gateway/public_data/otexa/HtsRepository.java, src/main/java/gov/ita/powerbi_gateway/public_data/otexa/ProductionMetadataService.java, src/main/java/gov/ita/powerbi_gateway/public_data/otexa/ScheduleB.java, src/main/java/gov/ita/powerbi_gateway/public_data/otexa/ScheduleBRepository.java
[21339] Otexa users see de-duplicated list of HTS/ScheduleB in pre-selection screen
=> [21339] Otexa users see de-duplicated list of HTS/ScheduleB in pre-selection screen

client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaExports.vue, src/main/resources/db/migration/R__1.00.49_CreateOtexaMonthlyImportsView.sql, src/main/resources/db/migration/R__1.00.51_CreateOtexaMonthlyFootwearViews.sql, src/main/resources/db/migration/V1.00.110__CreateOtexaMonthlyImportsTable.sql
- Monthly Imports
- Monthly Footwear Imports
- Monthly Footwear Exports
=> [22101] Otexa Monthly Data

client/src/reports/OtexaExports.vue, client/src/reports/OtexaMergedPartCat.vue
- Part & Merged category reports filtering incorrectly (vestiges of the old page level filter business)
- Export Data (all years) report needed to identify the correct table for underlying data, and remove filtering by Chapter & Schedule B
=> Otexa UI Bug Fixes:

client/src/reports/OtexaAnnual.vue, client/src/reports/OtexaExports.vue, client/src/reports/OtexaMergedPartCat.vue
- Increase height of some of the Category/Group, Chapter, and HTS/SchedB option lists
=> Change default pre-filter section screen to start with Category/Group rather than Country

client/src/reports/OtexaExports.vue, client/src/reports/OtexaMsrCategories.vue
And:
- remove the page navigation pane from Export reports
- remove Schedule B button from both Export MRS reports
=> [23897] Add a grouping for aggregate groups (groups 1-7) to the Export MSR Groups report

client/src/reports/OtexaTradeBalance.vue
- Always show aggregate groups
- Fixed issue where major countries appear along side regions
=> [24108] Otexa Trade Balance FTA Partners and Major Countries

client/src/reports/OtexaExports.vue, client/src/reports/OtexaMsrCategories.vue, client/src/reports/OtexaMsrCountries.vue
Export Data All Years - Major Country Groups not showing up
Export Data MSR Countries - Remove SME Option
Export Data MSR Groups - Remove SME Option, Add Group 0, Remove Group 2
Export Data - Country Groups not showing, remove hyphen "-" chapter
=> [24594] Fix Export Data Pre-Filters

client/src/reports/OtexaMsrCategories.vue, client/src/reports/OtexaMsrFootwearCategories.vue, src/main/resources/db/migration/R__1.00.48_OtexaHtsChapterRefView.sql
OTEXA MSR Category and MSR Group reports now allow users to select no filters and not have an error screen when submit button is clicked.
=> [27680] Fix OTEXA MSR Category and Group Reports displaying error when no filters are selected

src/main/resources/db/migration/R__CreateImauGatmViews.sql
[30594] IMAU users see consistent data with reverse flow in GATM Monitor
=> [30594] IMAU users see consistent data with reverse flow in GATM Monitor
